name: CI Grader

on: push

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: jitterbit/get-changed-files@v1
        id: files
        with:
          format: 'json'
      - name: Download Grader
        env:
          PROF_GITHUB: ${{ secrets.PROF_GITHUB }}
        run: |
          readarray -t added_modified_files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.added_modified }}')"
          for added_modified_file in "${added_modified_files[@]}"; do
            echo "${added_modified_file}" | cut -d "/" -f1
          done