name: CI Grader

on: push

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
      - name: Download Grader
        env:
          PROF_GITHUB: ${{ secrets.PROF_GITHUB }}
        run: /bin/bash .github/workflows/download.sh "${{ steps.files.outputs.added_modified }}"
#      - name: Install dependencies
#        run: /bin/bash .github/workflows/setup.sh
#      - name: Build image and send files
#        env:
#          RECIPE: ${{ secrets.RECIPE }}
#          COLLECTION_CONTAINER: ${{ secrets.COLLECTION_CONTAINER }}
#          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
#        run: /bin/bash .github/workflows/send.sh
