name: CI Grader

on: push

jobs:
  test:

    runs-on: ubuntu-latest
    container:
      image: ubuntu:21.10
      options: --privileged
    env:
      PROF_GITHUB: ${{ secrets.PROF_GITHUB }}

    steps:
      - uses: actions/checkout@v2
      - uses: jitterbit/get-changed-files@v1
        id: files
        with:
          format: 'json'
      - uses: actions/github-script@0.3.0
        id: author-date
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const commit_details = await github.git.getCommit({owner: context.repo.owner, repo: context.repo.repo, commit_sha: context.sha});
            return commit_details.data.author.date
      - name: Setup
        run: |
          apt-get -y update && apt-get -y install python3 python3-pip
          /usr/bin/python3 -m pip install requests
      - name: Grader
        env:
          COMMIT_TIME: ${{ steps.author-date.outputs.result }}
          COMMIT_FILES: ${{ steps.files.outputs.added_modified }}
        run: /usr/bin/python3 .github/workflows/grade.py