name: CI Grader

on: push

jobs:
  test:

    runs-on: ubuntu-latest
    env:
      PROF_GITHUB: ${{ secrets.PROF_GITHUB }}

    steps:
      - uses: actions/checkout@v2
      - uses: jitterbit/get-changed-files@v1
        id: files
        with:
          format: 'json'
      - name: Grader
        run: /bin/bash .github/workflows/grade.sh